### ISSUE TITLE
Restrict XMPP domain changes after initialization

### ISSUE THREAD

**Issue by pcbaldwin** [eglooca/app-openfire#4]
Changing the XMPP domain changes the XMPP address (ID) for existing users.  This can break pre-existing references (e.g.  roster entries).  Restrict editing this parameter after the first initialization.

**Comment by marclaporte** [comment]
Please don't restrict. A severe warning is enough. I could test with a few users on a bogus domain, and after, set the real domain.

**Comment by pcbaldwin** [comment]
Sounds good.  Warning only.
